#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
# Some GStreamer checks can cause issues, this can help
export GST_PLUGIN_SYSTEM_PATH_1_0=
# Run the main executable from the bundled app, passing all arguments
exec "$HERE/usr/bin/wallshuffle" "$@"
